language: lua

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks make

before_script:
  - luarocks install luacov-coveralls
  - luarocks install busted
  - PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
  # source: https://wiki.archlinux.org/index.php/ruby#Setup
  - gem install gist

script:
  - busted -c
  - curl -L http://git.io/vEdlr | cover_unrelated 1 | gist -a

after_success:
  - luacov
  - luacov-coveralls -v
